---

- name: Meet dependencies

  hosts:
    - all
  roles:
    - dependencies

  become: yes


- name: Install and configure Prometheus & Grafana

  hosts:
    - monitoring_servers
  roles:
    - server-role

  become: yes


- name: Install and configure Node Exporter

  hosts:
    - pi_servers
    - docker_servers
    - prox_servers
  roles:
    - node-exporter

  become: yes


- name: Deploy config files

  hosts:
    - monitoring_servers
  roles:
    - deploy-configs

  become: yes