---


- name: Clear config path
  file:
    path: "{{ item }}"
    state: "absent"
  become: true
  with_items:
    - "{{ prometheus_config }}"


- name: Create config folder
  file:
    path: "{{ item }}"
    state: "directory"
    mode: "0775"
    owner: "{{ monitoring_user }}"
    group: "{{ monitoring_group }}"
  become: true
  with_items:
    - "{{ prometheus_config }}"


- name: Deploy Prometheus config file
  template:
    mode: "0755"
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_config }}/prometheus.yml"

- name: Make sure a service is running
  systemd:
    state: restarted
    name: prometheus